### ISSUE TITLE
Stuck at 76% on .FR

### ISSUE THREAD

**Issue by TheRevenge** [LilithRainbows/HabboFlash#1]
It looks like Habbo patched this method and is blocking new connections. Sorry I don't have more details.
![image](https://user-images.githubusercontent.com/39599244/107638887-75988980-6c70-11eb-9d35-6f84e0f0f5b3.png)

**Comment by LilithRainbows** [comment]
It seems like connection to non-sandbox servers was disabled by Habbo.
I don't think I can fix it.
😥

**Comment by alanmondego** [comment]
Oh no please don't say that :'(
Just try!

**Comment by LilithRainbows** [comment]
Fixed
