### ISSUE TITLE
The client isn't working anymore (again).

### ISSUE THREAD

**Issue by ChristianViNhatLinh** [LilithRainbows/HabboFlash#11]
The problem seem to haven't been fixed yet, I still got disconnected whenever I try to login

**Comment by LilithRainbows** [comment]
Its working, download the client again at https://github.com/LilithRainbows/HabboFlash/releases/latest
![image](https://user-images.githubusercontent.com/44578053/210868903-9ea607a8-af3e-4201-9e1a-81f7be3cf51e.png)
